version: '3.8'

services:
  nginx:
    build:
      context: ./nginx
    container_name: nginx-app
    ports:
      - "80:80"
    depends_on:
      - php-fpm
      - db
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/site.html:/usr/share/nginx/html/site.html
      - ./nginx/index.php:/usr/share/nginx/html/index.php
      
    networks:
      - app-network

  db:
    build:
      context: ./mysql
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: moses1234
      MYSQL_DATABASE: inventory_db
      MYSQL_USER: mosesugwu
      MYSQL_PASSWORD: moses1234
    
    image: mysql:8.0
    ports:
      - "3306:3306"

    networks:
      - app-network

    volumes:
      - db-data:/var/lib/mysql
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  db-data:

networks:
  app-network:
    driver: bridge
