version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile-nginx
    ports:
      - "80:80"
    depends_on:
      - php-fpm
      - db
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./index.php:/usr/share/nginx/html/index.php

  php-fpm:
    build:
      context: .
      dockerfile: Dockerfile-php
    volumes:
      - ./index.php:/var/www/html/index.php

  db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: inventory_db
    volumes:
      - mysql-data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  mysql-data:
