version: '3.8'

services:
  nginx:
    build:
      context: ./nginx
    container_name: nginx-app
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/site.html:/usr/share/nginx/html/site.html
      - ./nginx/booking.html:/usr/share/nginx/html/booking.html
    depends_on:
      - db

  db:
    build:
      context: ./mysql
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: moses1234
      MYSQL_DATABASE: inventory_db
      MYSQL_USER: mosesugwu
      MYSQL_PASSWORD: moses1234
    volumes:
      - db-data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  db-data:
