FROM mysql:8.0

# # Environment variables for MySQL
# ENV MYSQL_ROOT_PASSWORD=your_mysql_password
# ENV MYSQL_DATABASE=inventory_db
# ENV MYSQL_USER=user
# ENV MYSQL_PASSWORD=password

# Expose port 3306
EXPOSE 3306

