name: Create Terraform code for tf-infrastructure folder

on:
    push:
        branches:
            - mosesdev
            # - main
        paths:
            - "Docker/infrastructure/**"
            - ".github/workflows/tf-infrastructure-deployment.yml"
env:
    terraform-version: "1.1.7"
    workdir: "Docker/infrastructure/" 
    TF_VAR_public_key: "${{ secrets.public_key }}" 
    TF_VAR_client_secret: "${{ secrets.client_secret }}"
    AZURE_CLIENT_ID: 49d663e0-c997-439d-b75f-bac184c474d8
    AZURE_TENANT_ID: 062b4bc0-fa03-4ff6-898f-318d88f23127


jobs:
    Terraform-deployments:
        runs-on: ubuntu-latest

        steps:
            - name: Git checkout
              uses: actions/checkout@v4

            - name: Terraform install version
              uses: hashicorp/setup-terraform@v3
              with:
                terraform_version: ${{ env.terraform-version}}
                
            - name: Install Azure CLI 
              run: |
                curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash

            - name: Azure CLI login
              run: az login --service-principal --username"${{ env.AZURE_CLIENT_ID }}" --password "${{ env.TF_VAR_client_secret }}" --tenant "${{ env.AZURE_TENANT_ID }}"


            - name: Terraform init
              run: cd ${{env.workdir}} && terraform init 

            - name: Terraform fmt
              run: cd ${{env.workdir}} && terraform fmt .

            - name: Terraform validate
              run: cd ${{env.workdir}} && terraform validate
              env:
                TF_VAR_public_key: "${{ secrets.public_key }}"
                TF_VAR_client_secret: "${{ secrets.client_secret }}" 

            - name: Terraform plan
              run: cd ${{env.workdir}} && terraform plan
              env:
                TF_VAR_public_key: "${{ secrets.public_key }}" 
                TF_VAR_client_secret: "${{ secrets.client_secret }}"

            - name: Terraform apply 
              run: cd ${{env.workdir}} && terraform apply -auto-approve
              env:
                TF_VAR_public_key: "${{ secrets.public_key }}" 
                TF_VAR_client_secret: "${{ secrets.client_secret }}"


            
            
              
              

