name: Create Terraform code for tf-infrastructure folder

on:
    push:
        branches:
            - mosesdev
            # - main
        paths:
            - "Docker/infrastructure/**"
            - ".github/workflows/tf-infrastructure-deployment.yml"
env:
    terraform-version: "1.1.7"

jobs:
    Terraform-deployments:
        runs-on: ubuntu-latest

        steps:
            - name: Git checkout
              uses: actions/checkout@v4

            - name: Terraform install version
              uses: hashicorp/setup-terraform@v3
              with:
                terraform_version: ${{ env.terraform-version}} 

            - name: list
              run: ls -l

            # - name: Terraform init
            #   run: terraform init 

            # - name: Terraform fmt
            #   run: terraform fmt -check

            # - name: Terraform validate
            #   run: terraform validate

            # - name: Terraform plan
            #   run: terraform plan

