name: Create Terraform code for tf-infrastructure folder

on:
    push:
        branches:
            - mosesdev
            # - main
        paths:
            - "Docker/infrastructure/**"
            - ".github/workflows/tf-infrastructure-deployment.yml"
env:
    terraform-version: "1.1.7"
    workdir: "Docker/infrastructure/" 
    TF_VAR_TOKEN: ${{ secrets.TOKEN }}
    TF_VAR_private_key: ${{ secrets.private_key }}
    TF_VAR_public_key: "${{ secrets.public_key }}" 
    TF_VAR_client_secret: "${{ secrets.client_secret }}"
    ARM_CLIENT_SECRET: "${{ secrets.client_secret }}" 
    ARM_CLIENT_ID: 49d663e0-c997-439d-b75f-bac184c474d8
    ARM_TENANT_ID: 062b4bc0-fa03-4ff6-898f-318d88f23127
    ARM_SUBSCRIPTION_ID: 3e58bbdc-9887-4d0f-af48-e47b110f81a5
    RESOURCE_GROUP: "rg-ce-mosesugwu-01"
    NSG_NAME: "nsg-ce-mosesugwu-dev-01"
    TF_VAR_custom_data_vm_1: "${{ github.workspace }}/Docker/infrastructure/scripts/docker_install.sh"
    TF_VAR_custom_data_vm_3: "${{ github.workspace }}/Docker/infrastructure/scripts/vault_install.sh"
    TF_VAR_custom_data_vm_2: "${{ github.workspace }}/Docker/infrastructure/scripts/ghrunner_install.sh"


jobs:
    Terraform-deployments:
        runs-on: ubuntu-latest #[self-hosted, linux, x64] 
           

        steps:
            - name: Git checkout
              uses: actions/checkout@v4

            - name: Install Node.js
              uses: actions/setup-node@v4
              with:
                node-version: '20'

            # - name: Copy private key to runner
            #   run: echo "${{ secrets.private_key }}" > $HOME/.ssh/moseskey
            #   shell: bash

            - name: Terraform install version
              uses: hashicorp/setup-terraform@v3
              with:
                terraform_version: ${{ env.terraform-version}}
                
            - name: Install Azure CLI 
              run: |
                curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash

            - name: Azure CLI login
              run: az login --service-principal --username "${{ env.ARM_CLIENT_ID }}" --password "${{ env.ARM_CLIENT_SECRET }}" --tenant "${{ env.ARM_TENANT_ID }}"

            - name: Get Runner IP
              id: get_ip
              run: |
                echo "PUBLIC_IP=$(curl -s https://ipinfo.io/ip)" >> $GITHUB_ENV
      
            # - name: Add NSG Rule
            #   run: |
            #     az network nsg rule create --resource-group ${{ env.RESOURCE_GROUP }} --nsg-name ${{ env.NSG_NAME }} \
            #       --name AllowGitHubActionsRunner --priority 300 --source-address-prefixes ${{ env.PUBLIC_IP }} \
            #       --destination-address-prefixes '*' --destination-port-ranges 8200 --direction Inbound --access Allow --protocol Tcp

            - name: Terraform init
              run: cd ${{ github.workspace }}/${{env.workdir}} && terraform init
              env:
                ARM_CLIENT_SECRET: "${{ env.ARM_CLIENT_SECRET }}" 
                ARM_CLIENT_ID: "${{ env.ARM_CLIENT_ID}}"
                ARM_TENANT_ID: "${{ env.ARM_TENANT_ID}}"
                ARM_SUBSCRIPTION_ID: "${{ env.ARM_SUBSCRIPTION_ID }}" 

            - name: Terraform fmt
              run: cd ${{ github.workspace }}/${{env.workdir}} && terraform fmt .
              env:
                ARM_CLIENT_SECRET: "${{ env.ARM_CLIENT_SECRET }}"
                ARM_CLIENT_ID: "${{ env.ARM_CLIENT_ID}}"
                ARM_TENANT_ID: "${{ env.ARM_TENANT_ID}}"
                ARM_SUBSCRIPTION_ID: "${{ env.ARM_SUBSCRIPTION_ID }}"

            - name: Terraform validate
              run: cd ${{ github.workspace }}/${{env.workdir}} && terraform validate
              env:
                TF_VAR_public_key: "${{ secrets.public_key }}"
                ARM_CLIENT_SECRET: "${{ env.ARM_CLIENT_SECRET }}"
                ARM_CLIENT_ID: "${{ env.ARM_CLIENT_ID}}"
                ARM_TENANT_ID: "${{ env.ARM_TENANT_ID}}"
                ARM_SUBSCRIPTION_ID: "${{ env.ARM_SUBSCRIPTION_ID }}" 


            - name: Debug TOKEN
              run: echo "TOKEN is set"
              env:
                TOKEN: ${{ secrets.TOKEN }}
  

            - name: Terraform plan
              run: cd ${{ github.workspace }}/${{env.workdir}} && terraform plan
              env:
                TF_VAR_TOKEN: ${{ secrets.TOKEN }}
                TF_VAR_public_key: "${{ secrets.public_key }}" 
                ARM_CLIENT_SECRET: "${{ env.ARM_CLIENT_SECRET }}"
                ARM_CLIENT_ID: "${{ env.ARM_CLIENT_ID}}"
                ARM_TENANT_ID: "${{ env.ARM_TENANT_ID}}"
                ARM_SUBSCRIPTION_ID: "${{ env.ARM_SUBSCRIPTION_ID }}"

            - name: Terraform apply 
              run: cd ${{ github.workspace }}/${{env.workdir}} && terraform apply -auto-approve
              env:
                TF_VAR_TOKEN: ${{ secrets.TOKEN }}
                TF_VAR_public_key: "${{ secrets.public_key }}" 
                ARM_CLIENT_SECRET: "${{ env.ARM_CLIENT_SECRET }}"
                ARM_CLIENT_ID: "${{ env.ARM_CLIENT_ID}}"
                ARM_TENANT_ID: "${{ env.ARM_TENANT_ID}}"
                ARM_SUBSCRIPTION_ID: "${{ env.ARM_SUBSCRIPTION_ID }}"

            - name: Remove NSG Rule
              if: always()
              run: |
                az network nsg rule delete --resource-group ${{ env.RESOURCE_GROUP }} --nsg-name ${{ env.NSG_NAME }} --name AllowGitHubActionsRunner




                















                























            
            
              
              

